### ISSUE TITLE
metahuman人物变形

### ISSUE THREAD

**Issue by Engineering-Course** [YaooYingg/UE5DemoProject#1]
![批注 2022-08-03 104143](https://user-images.githubusercontent.com/7713394/182514584-95d90ab4-da9b-4ac5-b33a-130884f26768.png)
![批注 2022-08-03 104247](https://user-images.githubusercontent.com/7713394/182514594-6c08289a-3fcf-43a5-960c-b91e816f049c.png)

请问是什么问题？遗漏了哪些操作呢？

**Comment by YaooYingg** [comment]
你好，这个应该是Axis Studio 那边BVH broadcasting中勾选了位移选项，取消勾选位移应该就能解决模型变形问题。



姚颖  YaoYing
QA Engineer | Department of QA
 
Noitom Technology Ltd.
5th Floor, Bldg A
28 Xinjiekouwai Blvd, Beijing 100088, China
Mobile: +86 13693088281
E-Mail: ***@***.***
 
发件人： Clay Gong
发送时间： 2022-08-03 11:00
收件人： YaooYingg/UE5DemoProject
抄送： Subscribed
主题： [YaooYingg/UE5DemoProject] metahuman人物变形 (Issue #1)

请问是什么问题？遗漏了哪些操作呢？

**Comment by YaooYingg** [comment]
请检查一下Axis studio 软件中BVH Broadcasting 中是否勾选了位移，如果勾选了位移就会出现这种变形问题 ，取消勾选可解决变形问题

**Comment by YaooYingg** [comment]
> ![批注 2022-08-03 104143](https://user-images.githubusercontent.com/7713394/182514584-95d90ab4-da9b-4ac5-b33a-130884f26768.png) ![批注 2022-08-03 104247](https://user-images.githubusercontent.com/7713394/182514594-6c08289a-3fcf-43a5-960c-b91e816f049c.png)
> 
> 请问是什么问题？遗漏了哪些操作呢？
请检查一下Axis studio 软件中BVH Broadcasting 中是否勾选了位移，如果勾选了位移就会出现这种变形问题 ，取消勾选可解决变形问题

**Comment by Engineering-Course** [comment]
> 

是这个原因，取消勾选位移后，显示正常了，感谢

**Comment by YaooYingg** [comment]
> > 
> 
> 是这个原因，取消勾选位移后，显示正常了，感谢

最新版本v1.2.16 插件已经发布啦，欢迎试用哟！

**Comment by Engineering-Course** [comment]
> > > 
> > 
> > 
> > 是这个原因，取消勾选位移后，显示正常了，感谢
> 
> 最新版本v1.2.16 插件已经发布啦，欢迎试用哟！

ok 感谢提醒
